[package]
name = "stated"
version = "0.1.0"
authors = ["Stephen Holsapple <sholsapp@gmail.com>"]

[dependencies]
clap = "2.12.1"
env_logger = "0.3.5"
futures = "0.1.6"
log = "0.3.6"
rustc-serialize = "0.3"
tokio-minihttp = { git = "https://github.com/tokio-rs/tokio-minihttp" }
tokio-proto = "0.1.1"
tokio-service = "0.1.0"
rand = "*"

[[bin]]
name = "stated-server"
path = "src/lib.rs"
